### ISSUE TITLE
Combining local and remote schema example doesn't work

### ISSUE THREAD

**Issue by MarcoMuellner** [ardatan/schema-stitching#323]
Cloning the repo, executing the start script, i get the following output:

```
[storefronts] [INFO] 10:18:08 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 5.3.2)
[products] [INFO] 10:18:08 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 5.3.2)
[gateway] [INFO] 10:18:08 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 5.3.2)
[products] products running at http://localhost:4001/graphql
[storefronts] storefronts  running at http://localhost:4001/graphql
[gateway] gateway running at http://localhost:4000/graphql
[gateway] TypeError: Cannot use 'in' operator to search for '_sdl' in null
[gateway]     at fetchRemoteSDL (/Users/marco/Documents/code/experimentation/schema-stitching/examples/combining-local-and-remote-schemas/src/gateway.ts:99:33)
[gateway]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[gateway]     at makeGatewaySchema (/Users/marco/Documents/code/experimentation/schema-stitching/examples/combining-local-and-remote-schemas/src/gateway.ts:47:29)
[gateway] [ERROR] 10:18:10 TypeError: Cannot use 'in' operator to search for '_sdl' in null
```

Ideally it would be great if the example works :)

**Comment by ardatan** [comment]
It seems to be working fine on CodeSandbox;
https://codesandbox.io/embed/github/ardatan/schema-stitching/tree/master/examples/combining-local-and-remote-schemas
Feel free to create a reproduction if it doesn't work :)
